// Quell — cookie-banner cosmetic layer.
// Registered dynamically by the background worker ONLY after the user enables
// "Cookie banners" and grants all-sites access. Three layers:
//   1. rules/cookie-generic.css — pipeline-generated generic selectors,
//      registered alongside this script and injected natively by Chrome.
//   2. This script's curated SEED set — hides top-CMP UI immediately, drives
//      the badge counter, and gates scroll-unlock.
//   3. Domain-specific selectors — requested from the background, which serves
//      only this host's slice of the pipeline-generated map.
// Rules derive from the open EasyList Cookie list (CC BY-SA 3.0 — see /NOTICE),
// regenerated by pipeline/build_rules.py.

(async () => {
  if (window.__quellCookies) return;
  window.__quellCookies = true;

  // Respect the master switch, the feature toggle, and the per-site pause.
  // (The background also unregisters this script when either toggle is off,
  // but pages loaded before that lands still get the right behavior.)
  let s = { enabled: true, cookieEnabled: true, cookieAllowlist: [] };
  try { s = await chrome.storage.local.get(s); } catch (_) { /* non-extension context (tests) */ }
  if (!s.enabled || !s.cookieEnabled) return;
  if ((s.cookieAllowlist || []).includes(location.hostname)) return;

  // Consent-UI containers only. NEVER put a CMP *state* class here (e.g.
  // `.didomi-popup-open` sits on <body> — hiding it blanks the whole page).
  const SEED = [
    '#onetrust-banner-sdk', '#onetrust-consent-sdk', '#onetrust-pc-sdk', '.onetrust-pc-dark-filter',
    '#CybotCookiebotDialog', '#CybotCookiebotDialogBodyUnderlay',
    '#cookiescript_injected',
    '#usercentrics-root', '#usercentrics-cmp-ui',
    'div[id^="sp_message_container"]',
    '.qc-cmp2-container', '.qc-cmp-cleanslate',
    '#didomi-host',
    '.truste_overlay', '.truste_box_overlay', '#truste-consent-track',
    '#cookieyes-banner', '.cky-consent-container', '.cky-overlay',
    '#cookie-law-info-bar', '#cookie-law-info-again',
    '#CookieConsent', '.cc-window.cc-banner', '.cookiecon-container',
    '.cookie-consent-banner', '#cookieConsentContainer'
  ];

  const addStyle = (id, css) => {
    if (document.getElementById(id)) return;
    const style = document.createElement('style');
    style.id = id;
    style.textContent = css;
    (document.head || document.documentElement).appendChild(style);
  };

  // Hide the consent UI. Scroll-unlock via CSS is scoped to CMP-added state
  // classes ONLY — a blanket html/body{overflow:auto} would break sites that
  // legitimately lock scroll (web apps, maps, lightboxes).
  addStyle('quell-cookies',
    SEED.join(',') + '{display:none!important;visibility:hidden!important;}' +
    'html.didomi-popup-open,body.didomi-popup-open,' +
    'html.sp-message-open,body.sp-message-open,' +
    'html.cky-overlay-open,body.cky-modal-open' +
    '{overflow:auto!important;}');

  // Domain-specific selectors for THIS host (tiny, host-sliced response).
  try {
    const resp = await chrome.runtime.sendMessage({ type: 'cookieSiteRules' });
    if (resp?.selectors?.length) {
      const sel = resp.selectors;
      const chunks = [];
      for (let i = 0; i < sel.length; i += 200) {
        chunks.push(sel.slice(i, i + 200).join(',') + '{display:none!important;}');
      }
      addStyle('quell-cookies-site', chunks.join('\n'));
    }
  } catch (_) { /* background asleep or non-extension context — seed still active */ }

  // JS scroll-unlock for CMPs that set overflow directly. Gated on having
  // actually hidden a consent element on THIS page, so a clean site's own
  // scroll-lock (modal, full-screen app) is never touched.
  let cmpSeen = false;
  const unlock = () => {
    if (!cmpSeen) return;
    for (const el of [document.documentElement, document.body]) {
      if (el && getComputedStyle(el).overflow === 'hidden') {
        el.style.setProperty('overflow', 'auto', 'important');
      }
    }
  };

  // Count banners we actually removed (once per element) for the popup counter.
  // Counting runs on the curated SEED only — scanning the full 15k-selector
  // generic list per mutation would be a page-wide perf tax.
  const sweep = () => {
    let n = 0;
    for (const sel of SEED) {
      for (const el of document.querySelectorAll(sel)) {
        if (el.dataset.quellSeen !== '1') {
          el.dataset.quellSeen = '1';
          n++;
        }
      }
    }
    if (n > 0) cmpSeen = true;
    unlock();
    if (n > 0) {
      try { chrome.runtime.sendMessage({ type: 'blocked', count: n }); } catch (_) { /* sw asleep */ }
    }
  };

  // CMPs inject late and mutate often — coalesce observer callbacks into one
  // sweep per frame instead of a full-document scan on every mutation.
  let scheduled = false;
  const schedule = () => {
    if (scheduled) return;
    scheduled = true;
    requestAnimationFrame(() => { scheduled = false; sweep(); });
  };

  if (document.body) sweep();
  new MutationObserver(schedule).observe(document.documentElement, { childList: true, subtree: true });
})();
