// Quell — cookie-banner cosmetic layer.
// Registered dynamically by the background worker ONLY after the user enables
// "Cookie banners" and grants all-sites access. Three layers:
//   1. rules/cookie-generic.css — pipeline-generated generic selectors,
//      registered alongside this script and injected natively by Chrome.
//   2. This script's curated SEED set — hides top-CMP UI immediately, drives
//      the badge counter, and gates scroll-unlock.
//   3. Domain-specific selectors — requested from the background, which serves
//      only this host's slice of the pipeline-generated map.
// Rules derive from the open EasyList Cookie list (CC BY-SA 3.0 — see /NOTICE),
// regenerated by pipeline/build_rules.py.
//
// Live-apply: this script owns layers 2 and 3, so toggling the feature (or the
// per-site pause) takes effect on the open page. Layer 1 is injected natively
// by Chrome from the registered content script; Chrome gives no way to pull
// that back out of an already-loaded page, so turning the feature OFF leaves
// the generic list active until the next load. The popup says so, and only
// when it's actually true.

(async () => {
  // Consent-UI containers only. NEVER put a CMP *state* class here (e.g.
  // `.didomi-popup-open` sits on <body> — hiding it blanks the whole page).
  const SEED = [
    '#onetrust-banner-sdk', '#onetrust-consent-sdk', '#onetrust-pc-sdk', '.onetrust-pc-dark-filter',
    '#CybotCookiebotDialog', '#CybotCookiebotDialogBodyUnderlay',
    '#cookiescript_injected',
    '#usercentrics-root', '#usercentrics-cmp-ui',
    'div[id^="sp_message_container"]',
    '.qc-cmp2-container', '.qc-cmp-cleanslate',
    '#didomi-host',
    '.truste_overlay', '.truste_box_overlay', '#truste-consent-track',
    '#cookieyes-banner', '.cky-consent-container', '.cky-overlay',
    '#cookie-law-info-bar', '#cookie-law-info-again',
    '#CookieConsent', '.cc-window.cc-banner', '.cookiecon-container',
    '.cookie-consent-banner', '#cookieConsentContainer'
  ];

  const DEFAULTS = { enabled: true, cookieEnabled: true, cookieAllowlist: [] };

  const addStyle = (id, css) => {
    if (document.getElementById(id)) return;
    const style = document.createElement('style');
    style.id = id;
    style.textContent = css;
    (document.head || document.documentElement).appendChild(style);
  };
  const dropStyle = (id) => document.getElementById(id)?.remove();

  // Remember the caller's own inline overflow so scroll-unlock is reversible.
  const priorOverflow = new Map();

  let active = false;
  let observer = null;
  let scheduled = false;
  let cmpSeen = false;

  // JS scroll-unlock for CMPs that set overflow directly. Gated on having
  // actually hidden a consent element on THIS page, so a clean site's own
  // scroll-lock (modal, full-screen app) is never touched.
  const unlock = () => {
    if (!cmpSeen) return;
    for (const el of [document.documentElement, document.body]) {
      if (el && getComputedStyle(el).overflow === 'hidden') {
        if (!priorOverflow.has(el)) priorOverflow.set(el, el.style.overflow || '');
        el.style.setProperty('overflow', 'auto', 'important');
      }
    }
  };

  const relock = () => {
    for (const [el, prev] of priorOverflow) {
      el.style.removeProperty('overflow');
      if (prev) el.style.overflow = prev;
    }
    priorOverflow.clear();
  };

  // Count banners we actually removed (once per element) for the popup counter.
  // Counting runs on the curated SEED only — scanning the full 15k-selector
  // generic list per mutation would be a page-wide perf tax.
  const sweep = () => {
    let n = 0;
    for (const sel of SEED) {
      for (const el of document.querySelectorAll(sel)) {
        if (el.dataset.quellSeen !== '1') {
          el.dataset.quellSeen = '1';
          n++;
        }
      }
    }
    if (n > 0) cmpSeen = true;
    unlock();
    if (n > 0) {
      try { chrome.runtime.sendMessage({ type: 'blocked', count: n }); } catch (_) { /* sw asleep */ }
    }
  };

  // CMPs inject late and mutate often — coalesce observer callbacks into one
  // sweep per frame instead of a full-document scan on every mutation.
  // rAF never fires in a hidden tab, so a background tab would keep its banner
  // until focused; fall back to a macrotask there. (cookies.js runs standalone,
  // without common.js, so this mirrors Quell.nextTick rather than calling it.)
  const schedule = () => {
    if (scheduled) return;
    scheduled = true;
    const run = () => { scheduled = false; if (observer) sweep(); };
    if (document.hidden) setTimeout(run, 0);
    else requestAnimationFrame(run);
  };

  async function apply() {
    if (active) return;
    active = true;

    // Hide the consent UI. Scroll-unlock via CSS is scoped to CMP-added state
    // classes ONLY — a blanket html/body{overflow:auto} would break sites that
    // legitimately lock scroll (web apps, maps, lightboxes).
    addStyle('quell-cookies',
      SEED.join(',') + '{display:none!important;visibility:hidden!important;}' +
      'html.didomi-popup-open,body.didomi-popup-open,' +
      'html.sp-message-open,body.sp-message-open,' +
      'html.cky-overlay-open,body.cky-modal-open' +
      '{overflow:auto!important;}');

    // Domain-specific selectors for THIS host (tiny, host-sliced response).
    try {
      const resp = await chrome.runtime.sendMessage({ type: 'cookieSiteRules' });
      if (active && resp?.selectors?.length) {
        const sel = resp.selectors;
        const chunks = [];
        for (let i = 0; i < sel.length; i += 200) {
          chunks.push(sel.slice(i, i + 200).join(',') + '{display:none!important;}');
        }
        addStyle('quell-cookies-site', chunks.join('\n'));
      }
    } catch (_) { /* background asleep or non-extension context — seed still active */ }

    if (!active) return; // toggled off while awaiting the background
    if (document.body) sweep();
    observer = new MutationObserver(schedule);
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }

  function teardown() {
    active = false;
    if (observer) { observer.disconnect(); observer = null; }
    dropStyle('quell-cookies');
    dropStyle('quell-cookies-site');
    relock();
    cmpSeen = false;
  }

  const applyState = (s) => {
    const paused = (s.cookieAllowlist || []).includes(location.hostname);
    if (s.enabled && s.cookieEnabled && !paused) apply();
    else teardown();
  };

  // Guard double-injection (the background injects into already-open tabs when
  // the feature is switched on). A second run must not re-register listeners —
  // but the FIRST run's listener keeps applying state, so live-apply survives.
  if (window.__quellCookies) return;
  window.__quellCookies = true;

  // Subscribe before the first async read — a toggle landing during that read
  // would otherwise be missed and the page would sit stale until reload.
  try {
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area !== 'local') return;
      if (!('enabled' in changes || 'cookieEnabled' in changes || 'cookieAllowlist' in changes)) return;
      chrome.storage.local.get(DEFAULTS).then(applyState).catch(() => {});
    });
  } catch (_) { /* no chrome.storage in test context */ }

  let s = DEFAULTS;
  try { s = await chrome.storage.local.get(DEFAULTS); } catch (_) { /* non-extension context (tests) */ }
  applyState(s);
})();
